import type {
  ActivityItem,
  Insight,
  Material,
  Recommendation,
  Resource,
  Student,
} from './types'

export const teacher = {
  name: 'Dr. Priya Menon',
  email: 'priya.menon@school.edu',
  subject: 'Computer Science & Mathematics',
  className: 'Grade 10 · Advanced Track',
}

export const studentUser = {
  name: 'Alex Rivera',
  email: 'alex.rivera@school.edu',
  level: 'Standard' as const,
  currentSubject: 'Database Systems & Mathematics',
  currentTopic: 'ER Model',
  streak: 6,
}

export const dashboardStats = {
  totalStudents: 32,
  avgPerformance: 74,
  gapsDetected: 11,
  atRisk: 4,
}

export const classTrend = {
  data: [62, 65, 63, 68, 71, 70, 74],
  labels: ['Wk 1', 'Wk 2', 'Wk 3', 'Wk 4', 'Wk 5', 'Wk 6', 'Wk 7'],
}

export const topicMasteryOverview = [
  { label: 'ER Model', value: 52 },
  { label: 'Algebra', value: 82 },
  { label: 'Functions', value: 76 },
  { label: 'Geometry', value: 69 },
  { label: 'Trig', value: 48 },
  { label: 'Calculus', value: 58 },
  { label: 'Stats', value: 71 },
]

export const recentQuizPerformance = [
  { label: 'Quiz 1', value: 78 },
  { label: 'Quiz 2', value: 72 },
  { label: 'Quiz 3', value: 66 },
  { label: 'Quiz 4', value: 81 },
  { label: 'Quiz 5', value: 74 },
]

export const activity: ActivityItem[] = [
  {
    id: 'a0',
    kind: 'upload',
    title: 'Featured DBMS material uploaded',
    detail: 'ER Model — Entity, Attribute, Relationship, Cardinality',
    time: 'Just now',
  },
  {
    id: 'a1',
    kind: 'upload',
    title: 'New material uploaded',
    detail: 'Trigonometric Identities — Lecture Slides',
    time: '12 min ago',
  },
  {
    id: 'a2',
    kind: 'quiz',
    title: 'Quiz generated',
    detail: '10 questions · ER Model · Standard level',
    time: '1 hour ago',
  },
  {
    id: 'a3',
    kind: 'analysis',
    title: 'Lesson analyzed',
    detail: 'ER Model Conceptual Design scored 84/100',
    time: '3 hours ago',
  },
  {
    id: 'a4',
    kind: 'gap',
    title: 'Learning gap detected',
    detail: '8 students struggling with Many-to-Many Cardinality Mapping',
    time: 'Yesterday',
  },
  {
    id: 'a5',
    kind: 'recommendation',
    title: 'Recommendations refreshed',
    detail: '14 personalized actions generated for the class',
    time: 'Yesterday',
  },
]

export const insights: Insight[] = [
  {
    id: 'i0',
    severity: 'critical',
    message: '8 students are struggling with M:N Cardinality & Junction Tables in ER Model.',
  },
  {
    id: 'i1',
    severity: 'critical',
    message: '8 students are struggling with Trigonometric Identities.',
  },
  {
    id: 'i2',
    severity: 'warning',
    message: 'Your latest lesson has low differentiation across levels.',
  },
  {
    id: 'i3',
    severity: 'warning',
    message: '3 students may need remedial content before the next unit.',
  },
  {
    id: 'i4',
    severity: 'info',
    message: 'Class engagement peaked during worked-example segments.',
  },
]

export const materials: Material[] = [
  {
    id: 'm-dbms',
    name: 'ER Model — Entity, Attribute, Relationship, Cardinality',
    subject: 'Database Management Systems',
    topic: 'ER Model',
    type: 'Slides',
    date: '2026-09-02',
    status: 'Processed',
    sizeKb: 3420,
  },
  {
    id: 'm1',
    name: 'Trigonometric Identities — Lecture Slides',
    subject: 'Mathematics',
    topic: 'Trigonometry',
    type: 'Slides',
    date: '2026-08-28',
    status: 'Processed',
    sizeKb: 2480,
  },
  {
    id: 'm2',
    name: 'Intro to Calculus Notes',
    subject: 'Mathematics',
    topic: 'Calculus',
    type: 'PDF',
    date: '2026-08-24',
    status: 'Processed',
    sizeKb: 1310,
  },
  {
    id: 'm3',
    name: 'Quadratic Functions Worksheet',
    subject: 'Mathematics',
    topic: 'Functions',
    type: 'Document',
    date: '2026-08-20',
    status: 'Needs Review',
    sizeKb: 540,
  },
  {
    id: 'm4',
    name: 'Geometry — Circle Theorems',
    subject: 'Mathematics',
    topic: 'Geometry',
    type: 'PDF',
    date: '2026-08-15',
    status: 'Processed',
    sizeKb: 980,
  },
  {
    id: 'm5',
    name: 'Statistics Primer',
    subject: 'Mathematics',
    topic: 'Statistics',
    type: 'Video',
    date: '2026-08-11',
    status: 'Processing',
    sizeKb: 45200,
  },
]

export const students: Student[] = [
  {
    id: 's1',
    name: 'Alex Rivera',
    email: 'alex.rivera@school.edu',
    grade: 'Grade 10',
    level: 'Standard',
    overallScore: 74,
    progress: 68,
    status: 'On Track',
    weakTopics: ['ER Model: Cardinality & Junction Tables', 'Trigonometric Identities'],
    strengths: ['Algebra', 'Linear Functions'],
    performanceTrend: [70, 72, 69, 74, 73, 76, 74],
    topicMastery: [
      { topic: 'ER Model', mastery: 52 },
      { topic: 'Algebra', mastery: 86 },
      { topic: 'Functions', mastery: 78 },
      { topic: 'Geometry', mastery: 72 },
      { topic: 'Trigonometric Identities', mastery: 48 },
      { topic: 'Statistics', mastery: 70 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 80 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 58 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 88 },
    ],
    nextActivities: [
      'Review Remedial Track: ER Model M:N Junction Tables',
      'Watch Visual Explanation: Crow’s Foot Notation',
      'Complete 4-question Formative Check Quiz',
    ],
  },
  {
    id: 's2',
    name: 'Maya Chen',
    email: 'maya.chen@school.edu',
    grade: 'Grade 10',
    level: 'Advanced',
    overallScore: 91,
    progress: 88,
    status: 'On Track',
    weakTopics: [],
    strengths: ['Calculus', 'ER Modeling', 'Trigonometry'],
    performanceTrend: [84, 86, 88, 90, 89, 92, 91],
    topicMastery: [
      { topic: 'ER Model', mastery: 94 },
      { topic: 'Algebra', mastery: 95 },
      { topic: 'Functions', mastery: 92 },
      { topic: 'Geometry', mastery: 88 },
      { topic: 'Trigonometric Identities', mastery: 90 },
      { topic: 'Statistics', mastery: 86 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 96 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 92 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 98 },
    ],
    nextActivities: ['Attempt Advanced Challenge Set', 'Explore Real-world Applications'],
  },
  {
    id: 's3',
    name: 'Jordan Blake',
    email: 'jordan.blake@school.edu',
    grade: 'Grade 10',
    level: 'Remedial',
    overallScore: 52,
    progress: 41,
    status: 'At Risk',
    weakTopics: ['ER Model', 'Trigonometric Identities', 'Functions'],
    strengths: ['Basic Arithmetic'],
    performanceTrend: [58, 55, 52, 49, 51, 50, 52],
    topicMastery: [
      { topic: 'ER Model', mastery: 38 },
      { topic: 'Algebra', mastery: 60 },
      { topic: 'Functions', mastery: 44 },
      { topic: 'Geometry', mastery: 55 },
      { topic: 'Trigonometric Identities', mastery: 32 },
      { topic: 'Statistics', mastery: 48 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 44 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 38 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 62 },
    ],
    nextActivities: [
      'Start Remedial Track: Foundations',
      'Guided worked examples',
      '1-on-1 support session',
    ],
  },
  {
    id: 's4',
    name: 'Sofia Martins',
    email: 'sofia.martins@school.edu',
    grade: 'Grade 10',
    level: 'Standard',
    overallScore: 66,
    progress: 59,
    status: 'Needs Attention',
    weakTopics: ['Geometry', 'ER Model: Weak Entities'],
    strengths: ['Statistics'],
    performanceTrend: [70, 68, 66, 64, 65, 67, 66],
    topicMastery: [
      { topic: 'ER Model', mastery: 58 },
      { topic: 'Algebra', mastery: 74 },
      { topic: 'Functions', mastery: 68 },
      { topic: 'Geometry', mastery: 55 },
      { topic: 'Trigonometric Identities', mastery: 50 },
      { topic: 'Statistics', mastery: 80 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 68 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 54 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 76 },
    ],
    nextActivities: ['Review Geometry basics', 'Practice Trig identities set A'],
  },
  {
    id: 's5',
    name: 'Liam O’Connor',
    email: 'liam.oconnor@school.edu',
    grade: 'Grade 10',
    level: 'Standard',
    overallScore: 79,
    progress: 74,
    status: 'On Track',
    weakTopics: ['Statistics'],
    strengths: ['Geometry', 'Algebra', 'ER Model'],
    performanceTrend: [72, 74, 76, 78, 77, 80, 79],
    topicMastery: [
      { topic: 'ER Model', mastery: 82 },
      { topic: 'Algebra', mastery: 84 },
      { topic: 'Functions', mastery: 80 },
      { topic: 'Geometry', mastery: 86 },
      { topic: 'Trigonometric Identities', mastery: 72 },
      { topic: 'Statistics', mastery: 62 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 82 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 78 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 84 },
    ],
    nextActivities: ['Strengthen Statistics fundamentals', 'Optional challenge quiz'],
  },
  {
    id: 's6',
    name: 'Aisha Khan',
    email: 'aisha.khan@school.edu',
    grade: 'Grade 10',
    level: 'Remedial',
    overallScore: 58,
    progress: 47,
    status: 'Needs Attention',
    weakTopics: ['Functions', 'ER Model: Cardinality'],
    strengths: ['Geometry'],
    performanceTrend: [54, 56, 55, 57, 58, 57, 58],
    topicMastery: [
      { topic: 'ER Model', mastery: 46 },
      { topic: 'Algebra', mastery: 62 },
      { topic: 'Functions', mastery: 48 },
      { topic: 'Geometry', mastery: 70 },
      { topic: 'Trigonometric Identities', mastery: 40 },
      { topic: 'Statistics', mastery: 55 },
    ],
    quizHistory: [
      { id: 'q1', title: 'Functions Check', date: 'Aug 26', score: 52 },
      { id: 'q2', title: 'Trig Basics', date: 'Aug 21', score: 46 },
      { id: 'q3', title: 'Algebra Review', date: 'Aug 14', score: 66 },
    ],
    nextActivities: ['Foundations of Functions', 'Guided Trig practice'],
  },
]

export const recommendations: Recommendation[] = [
  {
    id: 'r0',
    title: 'Review Remedial Track: ER Model M:N Junction Tables',
    reason: 'Low performance in ER Cardinality (52% mastery across 8 students)',
    difficulty: 'Remedial',
    estMinutes: 20,
    priority: 'High',
    actions: [
      'Assign Remedial Track: Noun/Verb ER Analogy',
      'Watch Visual Demonstration: Many-to-Many Decomposition',
      'Complete 4-question Check Quiz',
    ],
    studentName: 'Alex Rivera',
    topic: 'ER Model',
  },
  {
    id: 'r1',
    title: 'Review Remedial Lesson: Trigonometric Identities',
    reason: 'Low performance in Trigonometric Identities (48% mastery)',
    difficulty: 'Remedial',
    estMinutes: 20,
    priority: 'High',
    actions: ['Review Remedial Lesson', 'Watch Visual Explanation', 'Complete 5-question Practice Quiz'],
    studentName: 'Alex Rivera',
    topic: 'Trigonometric Identities',
  },
  {
    id: 'r2',
    title: 'Foundations Track: Functions',
    reason: 'Repeated errors on function composition and domains',
    difficulty: 'Remedial',
    estMinutes: 30,
    priority: 'High',
    actions: ['Start Remedial Track', 'Guided worked examples', 'Reattempt Assessment'],
    studentName: 'Jordan Blake',
    topic: 'Functions',
  },
  {
    id: 'r3',
    title: 'Advanced Challenge: Enterprise EER Modeling & Normalization',
    reason: 'High mastery (94%) — ready for stretch problems',
    difficulty: 'Advanced',
    estMinutes: 40,
    priority: 'Low',
    actions: ['Attempt EER Specialization Hierarchy', 'Formalize Ternary Decomposition'],
    studentName: 'Maya Chen',
    topic: 'ER Model',
  },
  {
    id: 'r4',
    title: 'Geometry Refresher: Circle Theorems',
    reason: 'Mastery dipped below class average this week',
    difficulty: 'Standard',
    estMinutes: 25,
    priority: 'Medium',
    actions: ['Review Lesson', 'Complete Practice Set B'],
    studentName: 'Sofia Martins',
    topic: 'Geometry',
  },
]

export const studentRecommendations: Recommendation[] = [
  {
    id: 'sr0',
    title: 'Remedial Track: ER Model Many-to-Many Relationships',
    reason: 'Your last check showed confusion on foreign keys in M:N tables (52% mastery)',
    difficulty: 'Remedial',
    estMinutes: 15,
    priority: 'High',
    actions: [
      'Study Remedial Track: School Database Analogy',
      'Review Step-by-Step Junction Table Demo',
      'Take 4-Question Adaptive Quiz',
    ],
    topic: 'ER Model',
  },
  {
    id: 'sr1',
    title: 'Review Remedial Lesson: Trigonometric Identities',
    reason: 'You scored 58% on Trig Basics — this will close the gap',
    difficulty: 'Remedial',
    estMinutes: 20,
    priority: 'High',
    actions: ['Review Remedial Lesson', 'Watch Visual Explanation', 'Complete 5-question Practice Quiz'],
    topic: 'Trigonometric Identities',
  },
  {
    id: 'sr2',
    title: 'Practice Quiz: Pythagorean Identity',
    reason: 'Targeted practice on your weakest sub-topic',
    difficulty: 'Standard',
    estMinutes: 15,
    priority: 'Medium',
    actions: ['Start Practice Quiz', 'Review mistakes with AI Tutor'],
    topic: 'Trigonometric Identities',
  },
]

export const resources: Resource[] = [
  {
    id: 'res-dbms-1',
    title: 'Visualizing ER Cardinality (1:1, 1:N, M:N)',
    type: 'Video',
    difficulty: 'Remedial',
    estMinutes: 8,
    reason: 'Clear visual mapping of Crow’s Foot and Chen notation',
    url: '#',
  },
  {
    id: 'res-dbms-2',
    title: 'Junction Tables Explained: Why M:N Needs a Third Table',
    type: 'Article',
    difficulty: 'Standard',
    estMinutes: 10,
    reason: 'Directly addresses your primary misconception on foreign key placement',
    url: '#',
  },
  {
    id: 'res-dbms-3',
    title: 'ER Diagram Cheat Sheet & Symbol Guide',
    type: 'Diagram',
    difficulty: 'Standard',
    estMinutes: 5,
    reason: 'Quick reference for weak entities, identifying relationships, and multi-valued attributes',
    url: '#',
  },
  {
    id: 'res1',
    title: 'Visualizing the Unit Circle',
    type: 'Video',
    difficulty: 'Remedial',
    estMinutes: 8,
    reason: 'Builds the intuition most students miss before identities',
    url: '#',
  },
  {
    id: 'res2',
    title: 'Proving the Pythagorean Identity',
    type: 'Article',
    difficulty: 'Standard',
    estMinutes: 12,
    reason: 'Directly targets your current learning gap',
    url: '#',
  },
]

export const sampleLessonPlan = `Lesson: Introduction to Database ER Modeling & Cardinality Constraints

Objective: Students will construct ER conceptual diagrams and correctly model 1:1, 1:N, and M:N relationships with foreign key placement.

Warm-up (5 min): Recall entities, attributes, and primary keys.
Direct instruction (20 min): Define Entity Sets, Attribute Types (Composite, Multi-valued), and Cardinality Ratios. Show worked example of Student-Course M:N mapping to a junction table.
Practice (15 min): Students model a Hospital Management scenario (Doctor, Patient, Treatment).
Wrap-up (5 min): Formative exit ticket with two schema mapping questions.`
